language: python
python:
    - "2.7"
install:
    - "python setup.py develop"
    - "pip install -r requirements.txt"
    - "pip install -r dev-requirements.txt"
    - "pip install coveralls"
script:
    - py.test --cov=enrique --cov-report term-missing
after_success:
    coveralls --verbose
